name: Batch Directory Listing

on:
  push:
    branches:
      - main
      - release
      - "**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  find-batch-dirs:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find batch directories
        id: set-matrix
        run: |
          # Trouver tous les dossiers commençant par batch_
          BATCH_DIRS=$(find . -maxdepth 1 -type d -name "batch_*" -printf "%f\n")
          # Créer la matrice JSON
          echo "matrix={\"include\":[$(echo "$BATCH_DIRS" | while read dir; do echo "{\"batch_dir\":\"$dir\"},"; done | sed '$ s/,$//')]}" >> $GITHUB_OUTPUT

  list-directory:
    needs: find-batch-dirs
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.find-batch-dirs.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List directory contents
        run: |
          echo "Listing contents of ${{ matrix.batch_dir }}:"
          ls -l ${{ matrix.batch_dir }}
