name: Batch Directory Listing

on:
  push:
    branches:
      - main
      - release
      - "**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  find-batch-dirs:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find batch directories
        id: set-matrix
        run: |
          # Trouver tous les dossiers commençant par batch_
          BATCH_DIRS=$(find . -maxdepth 1 -type d -name "batch_*" -printf "%f\n")
          # Créer la matrice JSON
          MATRIX="{\"include\":["
          while IFS= read -r dir; do
            if [ ! -z "$dir" ]; then
              MATRIX="$MATRIX{\"batch_dir\":\"$dir\"},"
            fi
          done <<< "$BATCH_DIRS"
          # Enlever la dernière virgule et fermer le JSON
          MATRIX="${MATRIX%,}]}"
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  list-directory:
    needs: find-batch-dirs
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.find-batch-dirs.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List directory contents
        run: |
          echo "Listing contents of ${{ matrix.batch_dir }}:"
          ls -l ${{ matrix.batch_dir }}
